### ISSUE TITLE
cond question

### ISSUE THREAD

**Issue by hanxuanliang** [noneback/go-taskflow#22]
Recently, I've been studying some workflow designs. I have a question regarding your project: 

`cond.Precede(subflow, subflow2)`: How do I know where the workflow will execute when the condition's result is true? How is the executor selected in this place?

**Comment by noneback** [comment]
In this scenario, `precede` sets dependency and maps the candidate node to the return value of precondition func in `NewCondition`. 

And as I mentioned, this repo tries to give a taskflow-like API， condition node has almost the same operation like [taskflow-cpp conditional tasking](https://taskflow.github.io/taskflow/ConditionalTasking.html).
