### ISSUE TITLE
TODO: reimplement thread safe queue 

### ISSUE THREAD

**Issue by noneback** [noneback/go-taskflow#25]
- Implement with golang generic and lockfree techs. 
- Make benchmark and compare with previous implementation
- Unit test coverage should be at least above 80%

ref:
- https://github.com/golang-design/lockfree/blob/master/queue.go
- https://github.com/noneback/go-taskflow/blob/main/utils/queue.go
- https://go.dev/doc/tutorial/generics

**Comment by noneback** [comment]
@SvRaining

**Comment by SvRaining** [comment]
Got it :neckbeard:
