### ISSUE TITLE
TODO: improve utils.Queue performance

### ISSUE THREAD

**Issue by noneback** [noneback/go-taskflow#30]

**Comment by derecknowayback** [comment]
maybe this one will help: https://github.com/enriquebris/goconcurrentqueue

**Comment by noneback** [comment]
This repo is way complex. I guess we don't need most of APIs it provides.BTW, lockfree queue is not suitable either.

**Comment by noneback** [comment]
If you want to participate in this repo, there is a more suitable task.

**Comment by noneback** [comment]
#38 @derecknowayback
