### ISSUE TITLE
Error handling?

### ISSUE THREAD

**Issue by zeisss** [noneback/go-taskflow#31]
Hey, saw this on hacker news and gave the README a look.

How would one do error handling?

The `loop` example shows to use shared variables between the steps to pass state. Would error handling also just involve checking an error state and doing nothing?

**Comment by noneback** [comment]
Hi, thanks for your attention! 

Regarding error handling,  the `errors` in golang are values. It is the user's job to handle it correctly.  So, you need to handle it in the tasks or just transform those operations into a condition node. (mapping `error` to `uint`, framework will help you choose the next task)

Only unrecovered `panic` needs to be addressed by the framework. Now, if it happens, the whole graph will be canceled, leaving the rest tasks undone.  This behavior may evolve someday. If you have some good thoughts, feel free to let me know.
